#!/bin/sh

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:easy-quest/aid-dotfiles.git"

if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi


if command -v zsh >/dev/null 2>&1; then
  echo "Bootstraping Zsh"
else
  apt install zsh
  exec zsh
  sh -c "$(curl -fsSL https://gitee.com/shmhlsy/oh-my-zsh-install.sh/raw/master/install.sh)" 
  apt-get install fonts-powerline
  git clone --depth=1 https://gitee.com/romkatv/powerlevel10k.git ~/powerlevel10k
fi


# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init
